# -*- coding: utf-8 -*-
"""Prova 3 de Comp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MHydJ06ewQyE_XZIughPAhkEioD3OFVE
"""

# Primeira questão da prova terminada!
try:
  numInt = int(input('Digite um número: ')) 
except:
    print('\033[31m Acho que você não colocou um número. :c\033[')
    print('\033[31m Tente novamente!\033[')
else:
  if (numInt <= 0):
    print('\033[31m [Erro]\033[')
    while (numInt <= 0):
      try:
        numInt = int(input('Digite um inteiro positivo: '))
      except:
        print('\033[31m Acho que você não colocou um número. :c\033[')
        print('\033[31m Tente novamente:\033[')
      else:
        if (numInt <= 0):
          print('\033[31m [Erro]\033[')
        else: 
          if numInt % 2 == 1:
            print('\033[1;32m O número é primo!!\033[')
          else:
            print('\033[31m O número não é primo!\033[')
  else:
    if numInt % 2 == 1:
        print('\033[1;32m O número é primo!!\033[')
    else:
        print('\033[31m O número não é primo!\033[')

# Segunda questão da prova terminada!
from time import sleep
matriz = [[0, 0], [0, 0]]
for l in range(0, 2): # linha
  for c in range(0,2): # coluna
    matriz[l][c] = int(input(f'Digite um valor [{l}, {c}]: ')) 
print('--' *13)
print('Essa é sua matriz A:')
print('--' *13)
for l in range(0, 2):
  for c in range(0, 2):
    print(f'[{matriz[l][c]:^5}]', end='')
  print()
print('--' *13)

a = (matriz[0][0] * matriz[0][0])
b = (matriz[0][1] * matriz[0][1])
c = (matriz[1][0] * matriz[1][0])
d = (matriz[1][1] * matriz[1][1])

matriz = [[a, b], [c, d]]

sleep(1)
print('O resultado do produto da matriz A por ela mesma é: ')
sleep(2)
print('--' *13)
print('Processando...')
print('--' *13)
sleep(2)
print('Seu resultado é:')
sleep(1)
print('--' *13)
for l in range(0, 2):
  for c in range(0, 2):
    print(f'\033[1;32m[{matriz[l][c]:^5}]\033[', end='')
  print()

# Terceira questão da prova, mas foi uma interpretação errada de que o jogador nunca perde!
from time import sleep
print(''' 
 [ A ] Pedra
 [ B ] Papel
 [ C ] Tesoura
 ''')

opcao = (input('Qual é a sua opção? '))
if opcao == 'A' or opcao == 'B' or opcao == 'C':
      print(' Jo')
      sleep(1)
      print(' Ken')
      sleep(1)
      print(' Pô!!!')
      sleep(1)
else:
   print('\033[31m Opção inválida.\033[')
   sleep(1)
   print('--' * 13)
   print('\033[31m Fim do programa! Volte sempre! :)\033[')
   
if opcao == 'A':
   print('Você escolheu Pedra.')
   sleep(1)
   print('\033[31m Computador escolheu Tesoura.\033[')
   sleep(1)
   print('\033[1;32m Você venceu!!')
   sleep(1)

if opcao == 'B':
   print('Você escolheu Papel.')
   sleep(1)
   print('\033[31m Computador escolheu Pedra.\033[')
   sleep(1)
   print('\033[1;32m Você venceu!!')
   sleep(1)

if opcao == 'C':
   print('Você escolheu Tesoura')
   sleep(1)
   print('\033[31m Computador escolheu Papel.\033[')
   sleep(1)
   print('\033[1;32m Você venceu!!')
   sleep(1)

# Terceira questão da prova terminada!
from time import sleep
from random import randint
def  lin():
    print ("--"*13)
itens = ('Pedra', 'Papel', 'Tesoura')
pc = randint(0, 2)
print ("""
       Escolhas:
       [ 0 ] Pedra
       [ 1 ] Papel
       [ 2 ] Tesoura""")
lin()
try:
  jogada = int(input("Qual é a sua escolha? "))
except:
    print('\033[31mO que você digitou não foi nem um número, já entendi que não deseja jogar. :c\033[')
else:
  if jogada == 0 or jogada == 1 or jogada == 2:
    print('  Jo')
    sleep(1)
    print('  Ken')
    sleep(1)
    print('  Pô!!!')
    sleep(1)
  if jogada == 0:
      if pc == 0:
          lin()
          print ("A sua jogada foi: {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;33m Empate!\033[')
          lin()
      elif pc == 1:
          lin()
          print ("A sua jogada foi: {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;32m O computador venceu!\033[')
          lin()
      elif pc == 2:
          lin()
          print ("A sua jogada foi: {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;32m Você venceu!\033[')
          lin()

  elif jogada == 1:
      if pc == 1:
          lin()
          print ("A sua jogada foi {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;33m Empate!\033[')
          lin()
      elif pc == 2:
          lin()
          print ("A sua jogada foi {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;32m O computador venceu!\033[')
          lin()
      elif pc == 0:
          lin()
          print ("A sua jogada foi {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;32m Você venceu!\033[')
          lin()

  elif jogada == 2:
      if pc == 2:
          lin()
          print ("A sua jogada foi {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;33m Empate!\033[')
          lin()
      elif pc == 0:
          lin()
          print ("A sua jogada foi {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;32m O computador venceu!\033[')
          lin()
      elif pc == 1:
          lin()
          print ("A sua jogada foi {}".format(itens[jogada]))
          print ("O computador jogou {}".format(itens[pc]))
          print ('\033[1;32m Você venceu!\033[')
          lin()
  else:
      print('\033[31m Opção inválida!\033[')
      print('\033[31m  Compile novamente caso deseje realmente jogar!\033[')